# Generated by Django 5.0.7 on 2024-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='accident_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
